## Data-analysis

##IMPORTACAO DOS DADOS

1.	Importar a tabela .csv

##TRATAMENTO DOS DADOS

2.	Organizar a planilha 
    Deletar linhas e colunas nao necessarias
    Identificar celulas vazias
    Etc
    
##ANALISE DOS DADOS
   
3.  Quantas empresas foram abertas no total?
4.  Quantas empresas foram abertas por segmento?
5.  Quais sao os tipos de empresas/segmentos - que tipo de servico elas fazem?
6.  Quantos funcionarios estao trabalhando em todas as empresas?
7.  Qual eh o segmento que tem mais funcionarios?

In [1]:
#1. Importar a tabela .csv

import pandas as pd
import numpy as np

df = pd.read_csv("Business_Licenses.csv")
display(df)

,X,Y,FID,PropertyNumber,Business_Name,Civic_Unit,Civic_House,Civic_Street,Mailing_Address,GISLink,...,NAICS_Primary,NAICS_Primary_Desc,Approved_Date,Permitted_Use,Permitted_Use_Desc,Seasonal_Employees,PartTime_Employees,FullTime_Employees,Latitude,Longitude
0,-13655110.99,6302015.650,1,150466,LINDSAY KENNEY BARRISTERS & SOLICITORS,400,8621.0,201 ST,400-8621 201 ST \nLANGLEY BC V2Y 0G9,148253.0,...,541110.0,"Professional, scientific & technical services ...",NaN,261,NaN,NaN,5.0,30.0,49.159776,-122.665949
1,NaN,NaN,2,136578,SITKA FIRE PROTECTION INC,NaN,NaN,OUT OF TOWN,207 8475 ONTARIO ST \nVANCOUVER BC V5X 3E8,136578.0,...,238220.0,Construction / Specialty trade contractors / B...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
2,-13654577.37,6305261.856,3,149216,WALNUT GROVE BOTTLE DEPOT,6,20280.0,97 AVE,8 20280 97 AVE \nLANGLEY BC V1M 4B9,149216.0,...,418190.0,Wholesale trade / Miscellaneous wholesaler-dis...,NaN,289,NaN,NaN,1.0,5.0,49.178842,-122.661156
3,-13650665.24,6291711.370,4,102680,CANADIAN MUSEUM FLIGHT ASSOCIATION,3,5333.0,216 ST,3-5333 216 ST \nLANGLEY BC V2Y 2N3,102680.0,...,712119.0,"Arts, entertainment & recreation / Heritage in...",NaN,NaN,NaN,NaN,NaN,NaN,49.099206,-122.626012
4,-13650331.94,6290096.797,5,109491,MURRAYVILLE COMMUNITY MEMORIAL HALL,NaN,21667.0,48 AVE,21667 48 AVE \nLANGLEY BC V3A 3M7,109491.0,...,813410.0,Other services (exc. Public administration) / ...,NaN,NaN,NaN,NaN,NaN,NaN,49.089709,-122.623018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7014,-13655593.26,6287954.262,7015,120750,CEDARBROOKS BAKERY LTD,NaN,4123.0,200 ST,4123 200 ST \nLANGLEY BC V3A 1K8,114407.0,...,311811.0,Manufacturing / Food mfg. / Bakeries & tortill...,NaN,83,NaN,NaN,NaN,NaN,49.077103,-122.670281
7015,-13633082.68,6284648.347,7016,122124,STEVE'S CUSTOM HOME LIGHTING (1982) LTD,NaN,27300.0,FRASER HWY,27294 FRASER HWY \nALDERGROVE BC V4W 3P8,112734.0,...,442110.0,Retail trade / Furniture & home furnishings st...,NaN,83,NaN,NaN,NaN,NaN,49.057646,-122.468065
7016,-13640632.83,6286425.635,7017,133634,OTTER FARM & HOME CO-OPERATIVE,NaN,3650.0,248 ST,3650 248 ST \nLANGLEY BC V4W 1X7,133634.0,...,452910.0,Retail trade / General merchandise stores / Ot...,NaN,309,NaN,NaN,NaN,NaN,49.068107,-122.535890
7017,-13633429.94,6284976.631,7018,133290,PEARCE HARDWARE (1977) LTD,NaN,3147.0,272 ST,BOX 1119 \n3147 272 ST \nALDERGROVE BC V4W 2V1,133290.0,...,444130.0,Retail trade / Building material & garden equi...,NaN,83,NaN,1.0,2.0,4.0,49.059578,-122.471185
7018,-13650508.65,6296054.182,7019,110595,NAPIER SALES LTD,NaN,6743.0,216 ST,6743 216 ST \nLANGLEY BC V2Y 0W9,110595.0,...,453310.0,Retail trade / Misc. store retailers / Used me...,NaN,127,NaN,NaN,3.0,NaN,49.124743,-122.624606

In [2]:
df.columns
list(df.columns)

['X',
 'Y',
 'FID',
 'PropertyNumber',
 'Business_Name',
 'Civic_Unit',
 'Civic_House',
 'Civic_Street',
 'Mailing_Address',
 'GISLink',
 'CommunityName',
 'Phone',
 'Licence_Desc',
 'Category',
 'Category_Desc',
 'Detail',
 'Detail_Desc',
 'NAICS_Primary',
 'NAICS_Primary_Desc',
 'Approved_Date',
 'Permitted_Use',
 'Permitted_Use_Desc',
 'Seasonal_Employees',
 'PartTime_Employees',
 'FullTime_Employees',
 'Latitude',
 'Longitude']

In [ ]:
# A tabela tem 7019 linhas e 27 colunas. Analisando a lista de colunas nesta tabela, varias colunas podem ser deletadas. 
# O proximo passo deleta-las para reduzir a tabela.

In [3]:
# Deletar as colunas q nao necessarias

df = df.drop(["X", "Y", "FID", "PropertyNumber","Business_Name","Civic_Unit", "Civic_House", "Civic_Street", "Mailing_Address","Detail", "GISLink", "Phone", "NAICS_Primary","Category","Permitted_Use", "Permitted_Use_Desc", "Latitude", "Longitude"], axis = 1) 
display(df)

,CommunityName,Licence_Desc,Category_Desc,Detail_Desc,NAICS_Primary_Desc,Approved_Date,Seasonal_Employees,PartTime_Employees,FullTime_Employees
0,Willoughby,LAW FIRM,PROFESSIONALS,LAWYER,"Professional, scientific & technical services ...",NaN,NaN,5.0,30.0
1,NaN,FIRE ALARM & WATER WORKS CONTRACTOR,CONTRACTOR - MISC,FIRE PROTECTION,Construction / Specialty trade contractors / B...,NaN,NaN,NaN,3.0
2,Northwest Langley,RECYCLING & BOTTLE DEPOT,GARBAGE COLLECTOR,RECYCLING EQUIPMENT,Wholesale trade / Miscellaneous wholesaler-dis...,NaN,NaN,1.0,5.0
3,Murrayville,FLIGHT MUSEUM,NaN,NaN,"Arts, entertainment & recreation / Heritage in...",NaN,NaN,NaN,NaN
4,Murrayville,COMMUNITY HALL,NON-PROFIT,SOCIETY,Other services (exc. Public administration) / ...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
7014,Brookswood / Fernridge,RETAIL,RETAIL MERCHANTS,BAKERY,Manufacturing / Food mfg. / Bakeries & tortill...,NaN,NaN,NaN,NaN
7015,Aldergrove,RETAIL,RETAIL MERCHANTS,HARDWARE STORE,Retail trade / Furniture & home furnishings st...,NaN,NaN,NaN,NaN
7016,NaN,RETAIL FOOD HARDWARE AND DRYGOODS,RETAIL MERCHANTS,HARDWARE STORE,Retail trade / General merchandise stores / Ot...,NaN,NaN,NaN,NaN
7017,Aldergrove,RETAIL HARDWARE,RETAIL MERCHANTS,HARDWARE STORE,Retail trade / Building material & garden equi...,NaN,1.0,2.0,4.0
7018,NaN,CHICK SALES/RETAIL ANTIQUES,RETAIL MERCHANTS,SECOND HAND STORE,Retail trade / Misc. store retailers / Used me...,NaN,NaN,3.0,NaN

In [ ]:
#Apos a deletion, restaram 9 colunas na tabela.

In [4]:
# info          # forma de verificar celulas vazias - imprimira um resumo de qtos valores nao nulos estao na tabela
                # essa forma tem que contar o complementar para saber qtas estao vazias. Ai entra a outra forma df.isna

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7019 entries, 0 to 7018
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CommunityName       4209 non-null   object
 1   Licence_Desc        7019 non-null   object
 2   Category_Desc       7011 non-null   object
 3   Detail_Desc         6914 non-null   object
 4   NAICS_Primary_Desc  6853 non-null   object
 5   Approved_Date       255 non-null    object
 6   Seasonal_Employees  4463 non-null   float64
 7   PartTime_Employees  5130 non-null   float64
 8   FullTime_Employees  6286 non-null   float64
dtypes: float64(3), object(6)
memory usage: 493.6+ KB
None

In [ ]:
# A tabela acima (info) mostra a qty de celulas vazias para cada coluna. 
#Ex.: P/coluna "CommunityName" -> total entries(= 7019) menos 4209 non-null = 2810 nao nulos
#Ex.: P/coluna "Licence_Desc" -> total entries(= 7019) menos 7019 non-null = zero celulas vazias

# Essa "info" tem a vantagem de descrever o tipo de variavel: 
# Ex que chama a atencao "Approved_Date" esta sendo reconhecido como object, mas deveria ser data

In [ ]:
# Alterando o tipo de variavel Object to data --> Approved_Date 
# Se fosse numerico seria: df["nome da coluna"] = pd.to_numeric(df["nome da coluna"], erros="coerce")
# coerce eh um codigo que na hora que houver a transformacao do tipo da variavel, o coerce fara c/ 
# q o campo fique vazio. 

# df["Approved_Date"] = pd.to_datetime(df["Approved_Date"], erros="coerce")

In [5]:
# df.isna().any()    or .sum()               # outra forma de verificar celulas vazias "isna -> eh vazio"

df.isna().any()
print(df.isna())

      CommunityName  Licence_Desc  Category_Desc  Detail_Desc  \
0             False         False          False        False
1              True         False          False        False
2             False         False          False        False
3             False         False           True         True
4             False         False          False        False
...             ...           ...            ...          ...
7014          False         False          False        False
7015          False         False          False        False
7016           True         False          False        False
7017          False         False          False        False
7018           True         False          False        False

      NAICS_Primary_Desc  Approved_Date  Seasonal_Employees  \
0                  False           True                True
1                  False           True                True
2                  False           True                True
3                  False           True                True
4                  False           True                True
...                  ...            ...                 ...
7014               False           True                True
7015               False           True                True
7016               False           True                True
7017               False           True               False
7018               False           True                True

      PartTime_Employees  FullTime_Employees
0                  False               False
1                   True               False
2                  False               False
3                   True                True
4                   True                True
...                  ...                 ...
7014                True                True
7015                True                True
7016                True                True
7017               False               False
7018               False                True

[7019 rows x 9 columns]

In [6]:
# df.isna().any()    or .sum()               # outra forma de verificar celulas vazias "isna -> is empty"

#df.isna().sum()
print(df.isna().sum())

CommunityName         2810
Licence_Desc             0
Category_Desc            8
Detail_Desc            105
NAICS_Primary_Desc     166
Approved_Date         6764
Seasonal_Employees    2556
PartTime_Employees    1889
FullTime_Employees     733
dtype: int64

In [ ]:
# Analisando essa forma acima de contar qtas celulas vazias essa eh mais direta.Ou seja, no geral, tem mais celulas
# vazias do que preenchidas

In [8]:
#Identificar alguns possiveis preenchimentos c vazios n hora de importar. Nesse caso nda mudara pq n ha essa situacao
#Valores_vazios = ["?", "-"]
#df = pd.read_csv("Business_Licenses.csv", na_values=valores_vazios)

#identificar com replace
df = df.replace({"?": np.nan, "-": np.nan})
display(df)

,CommunityName,Licence_Desc,Category_Desc,Detail_Desc,NAICS_Primary_Desc,Approved_Date,Seasonal_Employees,PartTime_Employees,FullTime_Employees
0,Willoughby,LAW FIRM,PROFESSIONALS,LAWYER,"Professional, scientific & technical services ...",NaN,NaN,5.0,30.0
1,NaN,FIRE ALARM & WATER WORKS CONTRACTOR,CONTRACTOR - MISC,FIRE PROTECTION,Construction / Specialty trade contractors / B...,NaN,NaN,NaN,3.0
2,Northwest Langley,RECYCLING & BOTTLE DEPOT,GARBAGE COLLECTOR,RECYCLING EQUIPMENT,Wholesale trade / Miscellaneous wholesaler-dis...,NaN,NaN,1.0,5.0
3,Murrayville,FLIGHT MUSEUM,NaN,NaN,"Arts, entertainment & recreation / Heritage in...",NaN,NaN,NaN,NaN
4,Murrayville,COMMUNITY HALL,NON-PROFIT,SOCIETY,Other services (exc. Public administration) / ...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
7014,Brookswood / Fernridge,RETAIL,RETAIL MERCHANTS,BAKERY,Manufacturing / Food mfg. / Bakeries & tortill...,NaN,NaN,NaN,NaN
7015,Aldergrove,RETAIL,RETAIL MERCHANTS,HARDWARE STORE,Retail trade / Furniture & home furnishings st...,NaN,NaN,NaN,NaN
7016,NaN,RETAIL FOOD HARDWARE AND DRYGOODS,RETAIL MERCHANTS,HARDWARE STORE,Retail trade / General merchandise stores / Ot...,NaN,NaN,NaN,NaN
7017,Aldergrove,RETAIL HARDWARE,RETAIL MERCHANTS,HARDWARE STORE,Retail trade / Building material & garden equi...,NaN,1.0,2.0,4.0
7018,NaN,CHICK SALES/RETAIL ANTIQUES,RETAIL MERCHANTS,SECOND HAND STORE,Retail trade / Misc. store retailers / Used me...,NaN,NaN,3.0,NaN

In [ ]:
#Removendo valores vazios

In [9]:
freq_bus_area = df["CommunityName"].value_counts()
display(freq_bus_area)

Willoughby                982
Willowbrook               634
Walnut Grove              492
Aldergrove                490
Brookswood / Fernridge    412
Murrayville               406
Northwest Langley         289
Gloucester                256
Fort Langley              248
Name: CommunityName, dtype: int64

In [10]:
freq_type_bus = df["Licence_Desc"].value_counts()
display(freq_type_bus)

RESIDENTIAL GENERAL CONTRACTOR                                                         120
MOTION PICTURE PRODUCTION                                                              107
GENERAL CONTRACTOR                                                                      86
ELECTRICAL CONTRACTOR                                                                   79
REGISTERED MASSAGE THERAPIST                                                            76
                                                                                      ...
EXCAVATION, EARTHMOVER CONTRACTOR                                                        1
OFFICE FOR E-COMMERCE BUSINESS FOR HOME DECOR                                            1
OFFICE FOR TREE SERVICE, PRUNING & REMOVALS                                              1
RESIDENTIAL & COMMERCIAL RESTORATION, RENOVATIONS & GENERAL CONTRACTOR - NO FRAMING      1
HOMEMADE NATURAL SOAPS                                                                   1
Name: Licence_Desc, Length: 4942, dtype: int64

In [11]:
freq_type_bus1 = df["Detail_Desc"].value_counts()
display(freq_type_bus1)

NOT USED                    493
SINGLE FAMILY DWELLING      292
MISCELLANEOUS               175
LANDSCAPING                 172
RESIDENTIAL & COMMERCIAL    153
                           ...
AQUATICS                      1
OFFICE                        1
SCHOOL CATERERS               1
HOT DOG CARTS                 1
RECYCLED MATERIALS            1
Name: Detail_Desc, Length: 480, dtype: int64